#!/usr/bin/env bash

langServersDir=/usr/local/bin/langServers

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -noverify \
    -Xms1G \
    -jar $langServersDir/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.*.jar \
    -configuration $langServersDir/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux/ \
    "$@"
